packages:
  - benchmark/react
  - examples/*
  - packages/background-only
  - packages/lynx/*
  - packages/mcp-servers/*
  - packages/repl
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/transform/rspack-napi
  - packages/react/transform/swc-plugin-reactlynx
  - packages/react/transform/swc-plugin-reactlynx-compat
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/tailwind-preset
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/motion
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - website

# From `@pnpm/plugin-better-defaults`
enablePrePostScripts: false
ignorePatchFailures: false
optimisticRepeatInstall: true
resolutionMode: "lowest-direct"

# Default catalogs
catalog:
  "@microsoft/api-extractor": "7.57.6"

catalogs:
  adb:
    "@yume-chan/adb": ^2.5.1
    "@yume-chan/adb-scrcpy": ^2.3.2
    "@yume-chan/adb-server-node-tcp": ^2.5.2
    "@yume-chan/async": ^2.1.0
    "@yume-chan/fetch-scrcpy-server": ^1.0.0
    "@yume-chan/scrcpy": ^2.3.0
    "@yume-chan/scrcpy-decoder-webcodecs": ^2.5.0
    "@yume-chan/stream-extra": ^2.1.0
    "@yume-chan/struct": ^2.1.0

  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.7.3"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.7.7"
    "@rspack/core": "1.7.7"
    "@rspack/test-tools": "1.5.6"

overrides:
  "@rspack/core": "$@rspack/core"
  "@rsbuild/core>@rspack/core": "$@rspack/core"

patchedDependencies:
  "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
  "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"

strictDepBuilds: true

onlyBuiltDependencies:
  - dprint
  - esbuild

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver
