/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_rawstyleinfo_free: (a: number, b: number) => void;
export const __wbg_rule_free: (a: number, b: number) => void;
export const __wbg_ruleprelude_free: (a: number, b: number) => void;
export const __wbg_selector_free: (a: number, b: number) => void;
export const __wbg_styleinfodecoder_free: (a: number, b: number) => void;
export const decode_style_info: (a: any, b: number, c: number, d: number) => [number, number, number];
export const encode_legacy_json_generated_raw_style_info: (a: number, b: number, c: number, d: number) => [number, number, number];
export const get_font_face_content: (a: any) => [number, number, number, number];
export const get_style_content: (a: any) => [number, number, number, number];
export const rawstyleinfo_append_import: (a: number, b: number, c: number) => void;
export const rawstyleinfo_encode: (a: number) => [number, number, number];
export const rawstyleinfo_new: () => number;
export const rawstyleinfo_push_rule: (a: number, b: number, c: number) => void;
export const rule_new: (a: number, b: number) => [number, number, number];
export const rule_push_declaration: (a: number, b: number, c: number, d: number, e: number) => void;
export const rule_push_rule_children: (a: number, b: number) => void;
export const rule_set_prelude: (a: number, b: number) => void;
export const ruleprelude_new: () => number;
export const ruleprelude_push_selector: (a: number, b: number) => void;
export const selector_push_one_selector_section: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const selector_new: () => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
