name: Reusable Test
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
      LHCI_GITHUB_APP_TOKEN:
        required: false
    inputs:
      runs-on:
        required: true
        type: string
      run:
        required: true
        type: string
        description: "Command run parameters, limited to predefined test commands"
      is-web:
        required: false
        type: boolean
        default: false
      web-report-name:
        required: false
        type: string
        default: "playwright-report"
      web-report-path:
        required: false
        type: string
        default: "packages/web-platform/web-tests/playwright-report"
      codecov-flags:
        required: false
        type: string
        default: "unittest"

# Set minimum permissions to prevent unnecessary access
permissions: {}

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  check:
    timeout-minutes: 30
    runs-on: ${{ inputs.runs-on }}
    permissions: {}
    container:
      image: ${{ inputs.is-web && 'mcr.microsoft.com/playwright:v1.58.2-noble' || null }}
      env:
        CI: 1
        TURBO_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          # Codecov requires fetch-depth: 0
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "22"
          package-manager-cache: false
      - name: TurboCache
        uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
        with:
          path: .turbo
          # We have to be strict here to make sure getting the cache of build-all
          key: turbo-v4-${{ runner.os }}-${{ hashFiles('**/packages/**/src/**/*.rs') }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Install
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm turbo build --summarize
      - name: Test # zizmor: ignore[template-injection] The inputs.run is provided by us.
        id: test
        env:
          NODE_OPTIONS: --max-old-space-size=16384
          GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: ${{ inputs.run }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ inputs.codecov-flags }}
          override_branch: ${{ github.event_name == 'merge_group' && 'main' || '' }}
      - name: Upload Test Result
        if: ${{ inputs.is-web && failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ inputs.web-report-name }}
          path: ${{ inputs.web-report-path }}
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: true
